#!/bin/sh
ADRESS=$(ifconfig | grep broadcast | cut -d ' ' -f 2)
CLUSTER=$(echo $ADRESS | cut -b 5)
ROW=$(echo $ADRESS | cut -d '.' -f 3)
PLACE=$(echo $ADRESS | cut -d '.' -f 4)
echo you are at e${CLUSTER}r${ROW}p${PLACE}
